name: buildAndDeploy
on:
  push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 我们选择使用最新的ubuntu系统
    steps:
    - name: checkout
      uses: actions/checkout@master # 将代码拷贝到虚机中

    - name: build
      run: |
          yarn install
          yarn build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        # 该workflow需要操作repo，因此需要一个密钥，下面会讲到如何获取这个密钥
        ACCESS_TOKEN: ${{ secrets.SECRET_TOKEN }}
        # 发布到的分支
        BRANCH: gh-pages
        # 要发布的文件夹
        FOLDER: dist
